#!/bin/bash

version=$1
base_version="${version%.*}"

# Download and extract mediawiki
wget http://releases.wikimedia.org/mediawiki/${base_version}/mediawiki-${version}.tar.gz
tar xf mediawiki-${version}.tar.gz
rm -f mediawiki-${version}.tar.gz

cd mediawiki-${version}/extensions
../../libs/install-extensions
